services:
  rust-server:
    build:
      context: ./rust-server
      args:
        STEAMAPPID: ${STEAMAPPID}
        STEAMAPPNAME: ${STEAMAPPNAME}
    container_name: rust
    volumes:
      - ./rustdata:/rust
    ports:
      - "${SERVER_PORT}:28015/tcp"
      - "${SERVER_PORT}:28015/udp"
      - "28016:28016/udp"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SERVER_IDENTITY: ${SERVER_IDENTITY}
      SERVER_SEED: ${SERVER_SEED}
      SERVER_WORLDSIZE: ${SERVER_WORLDSIZE}
      SERVER_MAXPLAYERS: ${SERVER_MAXPLAYERS}
      SERVER_SAVEINTERVAL: ${SERVER_SAVEINTERVAL}
      RCON_PASSWORD: ${RCON_PASSWORD}
    restart: unless-stopped

  rust-panel:
    build:
      context: ./panel
    container_name: rust-panel
    ports:
      - "8080:80"
    environment:
      RCON_HOST: rust
      RCON_PORT: 28016
      RCON_PASSWORD: ${RCON_PASSWORD}
    restart: unless-stopped
